services:
  postgres:
    image: postgres:17.2
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: assignment_db
      POSTGRES_USER: assignment_user
      POSTGRES_PASSWORD: password2
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata: {}